#!/usr/bin/env python3
"""Generate the launcher icon: both vector layers and the store PNG.

    python3 tools/gen-icon.py

Writes, from the one set of shapes below:

    app/src/main/res/drawable/ic_launcher_terminal.xml    foreground
    app/src/main/res/drawable/ic_launcher_monochrome.xml  themed icons
    fastlane/metadata/android/en-US/images/icon.png      512 x 512

The background layer is @color/ic_launcher_background, solid black, and has
no geometry. Deterministic: rerun it and the three files come out byte for
byte the same, so the committed PNG can be checked against the XML by
regenerating and diffing. Change a shape here, rerun, commit all four files.

The design, on the 108 x 108 adaptive canvas:

    a terminal window, outer edge x 30..78, y 32..76, corners rounded 4,
    sides and bottom 4 thick, a solid 8 thick title bar along the top;
    a "$" drawn as a pixel glyph from 4 x 4 bars, x 40..52, y 43..69;
    a block cursor, x 57..66, y 51..65.

Everything sits inside the 66dp safe zone (a circle of radius 33 about the
centre, 54,54): the frame's farthest point is the outside of a rounded
corner, about 30.9 from the centre. Nothing is thinner than 4, so the icon
survives being drawn at 48dp. LauncherIconTest checks both from the XML.

The PNG is what a launcher shows: the 72dp visible region (x and y 18..90)
of the black background and the foreground, masked to a circle, on a
transparent background, supersampled 4 x 4 per pixel.

Pure ASCII, standard library only.
"""
import math
import os
import struct
import zlib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
DRAWABLE = os.path.join(ROOT, "app", "src", "main", "res", "drawable")
PNG_PATH = os.path.join(ROOT, "fastlane", "metadata", "android", "en-US", "images", "icon.png")

# Must equal PhosphorGreen and JitterBackground in ui/theme/Color.kt, and the
# two colour resources; LauncherIconTest asserts the resources.
GREEN = (0x50, 0xFA, 0x7B)
BLACK = (0x00, 0x00, 0x00)

# (x0, y0, x1, y1, corner radius)
FRAME_OUTER = (30, 32, 78, 76, 4)
FRAME_INNER = (34, 40, 74, 72, 0)

# The "$": three bars, two verticals, and a stub above and below.
DOLLAR = [
    (44, 43, 48, 47),  # top stub
    (40, 47, 52, 51),  # top bar
    (40, 47, 44, 58),  # upper left vertical
    (40, 54, 52, 58),  # middle bar
    (48, 54, 52, 65),  # lower right vertical
    (40, 61, 52, 65),  # bottom bar
    (44, 65, 48, 69),  # bottom stub
]
CURSOR = (57, 51, 66, 65)

SIZE = 512
VISIBLE = (18.0, 90.0)
SS = 4


def num(v):
    return str(int(v)) if float(v).is_integer() else repr(v)


def rect_path(r):
    x0, y0, x1, y1 = r[:4]
    return "M%s,%s H%s V%s H%s Z" % (num(x0), num(y0), num(x1), num(y1), num(x0))


def rounded_path(r):
    x0, y0, x1, y1, c = r
    return (
        "M%s,%s H%s A%s,%s 0 0 1 %s,%s V%s A%s,%s 0 0 1 %s,%s "
        "H%s A%s,%s 0 0 1 %s,%s V%s A%s,%s 0 0 1 %s,%s Z"
    ) % tuple(num(v) for v in (
        x0 + c, y0, x1 - c, c, c, x1, y0 + c,
        y1 - c, c, c, x1 - c, y1,
        x0 + c, c, c, x0, y1 - c,
        y0 + c, c, c, x0 + c, y0,
    ))


def vector(comment):
    frame = rounded_path(FRAME_OUTER) + " " + rect_path(FRAME_INNER)
    glyph = " ".join(rect_path(r) for r in DOLLAR + [CURSOR])
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/gen-icon.py. Edit the script, not this file. -->\n"
        "<!-- %s -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        "    <path\n"
        '        android:name="frame"\n'
        '        android:fillColor="@color/phosphor_green"\n'
        '        android:fillType="evenOdd"\n'
        '        android:pathData="%s"/>\n'
        "    <path\n"
        '        android:name="prompt"\n'
        '        android:fillColor="@color/phosphor_green"\n'
        '        android:pathData="%s"/>\n'
        "</vector>\n"
    ) % (comment, frame, glyph)


def in_rect(x, y, r):
    return r[0] <= x < r[2] and r[1] <= y < r[3]


def in_rounded(x, y, r):
    x0, y0, x1, y1, c = r
    if not in_rect(x, y, r):
        return False
    cx = min(max(x, x0 + c), x1 - c)
    cy = min(max(y, y0 + c), y1 - c)
    return (x - cx) ** 2 + (y - cy) ** 2 <= c * c


def green_at(x, y):
    if in_rounded(x, y, FRAME_OUTER) and not in_rect(x, y, FRAME_INNER):
        return True
    return any(in_rect(x, y, r) for r in DOLLAR + [CURSOR])


def render():
    lo, hi = VISIBLE
    scale = (hi - lo) / SIZE
    radius = (hi - lo) / 2.0
    centre = (lo + hi) / 2.0
    rows = []
    for py in range(SIZE):
        row = bytearray([0])  # filter: none
        for px in range(SIZE):
            inside = 0
            lit = 0
            for sy in range(SS):
                y = lo + (py + (sy + 0.5) / SS) * scale
                for sx in range(SS):
                    x = lo + (px + (sx + 0.5) / SS) * scale
                    if (x - centre) ** 2 + (y - centre) ** 2 > radius * radius:
                        continue
                    inside += 1
                    if green_at(x, y):
                        lit += 1
            if inside == 0:
                row += bytes((0, 0, 0, 0))
                continue
            f = lit / inside
            rgb = [int(round(BLACK[i] + (GREEN[i] - BLACK[i]) * f)) for i in range(3)]
            alpha = int(round(255 * inside / (SS * SS)))
            row += bytes(rgb + [alpha])
        rows.append(bytes(row))
    return b"".join(rows)


def png(raw):
    def chunk(kind, data):
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0)  # 8-bit RGBA
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def write(path, data):
    mode = "wb" if isinstance(data, bytes) else "w"
    kwargs = {} if mode == "wb" else {"newline": "\n", "encoding": "ascii"}
    with open(path, mode, **kwargs) as f:
        f.write(data)


def main():
    write(os.path.join(DRAWABLE, "ic_launcher_terminal.xml"),
          vector("Foreground: a terminal window and a $ prompt with a block cursor."))
    write(os.path.join(DRAWABLE, "ic_launcher_monochrome.xml"),
          vector("Monochrome, for themed icons. The same shapes; the system uses only their alpha."))
    write(PNG_PATH, png(render()))


if __name__ == "__main__":
    main()
