#!/usr/bin/env python3
"""Generate the launcher icon: both vector layers and the store PNG.

    python3 tools/gen-icon.py

Writes, from the one set of shapes below:

    app/src/main/res/drawable/ic_launcher_terminal.xml    foreground
    app/src/main/res/drawable/ic_launcher_monochrome.xml  themed icons
    fastlane/metadata/android/en-US/images/icon.png      512 x 512

The background layer is @color/ic_launcher_background, solid black, and has
no geometry. Deterministic: rerun it and the three files come out byte for
byte the same, so the committed PNG can be checked against the XML by
regenerating and diffing. Change a shape here, rerun, commit all four files.

The design, on the 108 x 108 adaptive canvas: ">_" and nothing else. No
frame, because a rounded outline read as a card and a lone "$" as money.

    chevron     a 90 degree ">" stroked at 3.5*sqrt(2) = 4.95 thick, with
                flat ends cut square to each arm and a mitred tip. Its centre
                line runs 35.25,41 -> 48.25,54 -> 35.25,67, and the outline is
                the six points in CHEVRON below: x 33.5..51.75,
                y 39.25..68.75.
    underscore  a bar x 56.5..74.5, y 63.75..68.75, 5 thick. Its bottom is
                the chevron's bottom, 68.75: the baseline they share.

The pair spans x 33.5..74.5 (41 wide) and y 39.25..68.75, so the group's box
is centred on 54,54. Its farthest point from the centre is the underscore's
bottom right corner, about 25.3 away, well inside the 66dp safe zone (a
circle of radius 33). Both shapes are 4.95 to 5 thick: thinned from 7 on
device, where 7 read as heavy, and still bold enough for 48dp.
LauncherIconTest checks all of this from the XML.

The PNG is what a launcher shows: the 72dp visible region (x and y 18..90)
of the black background and the foreground, masked to a circle, on a
transparent background, supersampled 4 x 4 per pixel.

Pure ASCII, standard library only.
"""
import math
import os
import struct
import zlib

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
DRAWABLE = os.path.join(ROOT, "app", "src", "main", "res", "drawable")
PNG_PATH = os.path.join(ROOT, "fastlane", "metadata", "android", "en-US", "images", "icon.png")

# Must equal PhosphorGreen and JitterBackground in ui/theme/Color.kt, and the
# two colour resources; LauncherIconTest asserts the resources.
GREEN = (0x50, 0xFA, 0x7B)
BLACK = (0x00, 0x00, 0x00)

# The ">" as the outline of a stroke: offset 1.75 each side of the centre
# line along the arm's normal (so 3.5*sqrt(2) = 4.95 thick), flat ends square
# to each arm, and a mitred tip where the two outer edges meet.
CHEVRON = [
    (33.5, 42.75),  # top end, inner
    (37.0, 39.25),  # top end, outer
    (51.75, 54.0),  # tip, outer (mitre)
    (37.0, 68.75),  # bottom end, outer
    (33.5, 65.25),  # bottom end, inner
    (44.75, 54.0),  # tip, inner (mitre)
]
# (x0, y0, x1, y1)
UNDERSCORE = (56.5, 63.75, 74.5, 68.75)

SIZE = 512
VISIBLE = (18.0, 90.0)
SS = 4


def num(v):
    return str(int(v)) if float(v).is_integer() else repr(v)


def rect_path(r):
    x0, y0, x1, y1 = r
    return "M%s,%s H%s V%s H%s Z" % (num(x0), num(y0), num(x1), num(y1), num(x0))


def polygon_path(points):
    head = "M%s,%s" % (num(points[0][0]), num(points[0][1]))
    rest = " ".join("L%s,%s" % (num(x), num(y)) for x, y in points[1:])
    return head + " " + rest + " Z"


def vector(comment):
    return (
        '<?xml version="1.0" encoding="utf-8"?>\n'
        "<!-- Generated by tools/gen-icon.py. Edit the script, not this file. -->\n"
        "<!-- %s -->\n"
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp"\n'
        '    android:height="108dp"\n'
        '    android:viewportWidth="108"\n'
        '    android:viewportHeight="108">\n'
        "    <path\n"
        '        android:name="chevron"\n'
        '        android:fillColor="@color/phosphor_green"\n'
        '        android:pathData="%s"/>\n'
        "    <path\n"
        '        android:name="underscore"\n'
        '        android:fillColor="@color/phosphor_green"\n'
        '        android:pathData="%s"/>\n'
        "</vector>\n"
    ) % (comment, polygon_path(CHEVRON), rect_path(UNDERSCORE))


def in_rect(x, y, r):
    return r[0] <= x < r[2] and r[1] <= y < r[3]


def in_polygon(x, y, points):
    """Even-odd ray cast. The chevron is simple, so even-odd and non-zero agree."""
    inside = False
    n = len(points)
    for i in range(n):
        x0, y0 = points[i]
        x1, y1 = points[(i + 1) % n]
        if (y0 > y) != (y1 > y):
            cross = x0 + (y - y0) * (x1 - x0) / (y1 - y0)
            if x < cross:
                inside = not inside
    return inside


def green_at(x, y):
    return in_polygon(x, y, CHEVRON) or in_rect(x, y, UNDERSCORE)


def render():
    lo, hi = VISIBLE
    scale = (hi - lo) / SIZE
    radius = (hi - lo) / 2.0
    centre = (lo + hi) / 2.0
    rows = []
    for py in range(SIZE):
        row = bytearray([0])  # filter: none
        for px in range(SIZE):
            inside = 0
            lit = 0
            for sy in range(SS):
                y = lo + (py + (sy + 0.5) / SS) * scale
                for sx in range(SS):
                    x = lo + (px + (sx + 0.5) / SS) * scale
                    if (x - centre) ** 2 + (y - centre) ** 2 > radius * radius:
                        continue
                    inside += 1
                    if green_at(x, y):
                        lit += 1
            if inside == 0:
                row += bytes((0, 0, 0, 0))
                continue
            f = lit / inside
            rgb = [int(round(BLACK[i] + (GREEN[i] - BLACK[i]) * f)) for i in range(3)]
            alpha = int(round(255 * inside / (SS * SS)))
            row += bytes(rgb + [alpha])
        rows.append(bytes(row))
    return b"".join(rows)


def png(raw):
    def chunk(kind, data):
        body = kind + data
        return struct.pack(">I", len(data)) + body + struct.pack(">I", zlib.crc32(body) & 0xFFFFFFFF)

    header = struct.pack(">IIBBBBB", SIZE, SIZE, 8, 6, 0, 0, 0)  # 8-bit RGBA
    return (
        b"\x89PNG\r\n\x1a\n"
        + chunk(b"IHDR", header)
        + chunk(b"IDAT", zlib.compress(raw, 9))
        + chunk(b"IEND", b"")
    )


def write(path, data):
    mode = "wb" if isinstance(data, bytes) else "w"
    kwargs = {} if mode == "wb" else {"newline": "\n", "encoding": "ascii"}
    with open(path, mode, **kwargs) as f:
        f.write(data)


def main():
    write(os.path.join(DRAWABLE, "ic_launcher_terminal.xml"),
          vector("Foreground: a > prompt and an _ cursor, and nothing else."))
    write(os.path.join(DRAWABLE, "ic_launcher_monochrome.xml"),
          vector("Monochrome, for themed icons. The same shapes, fully opaque; the system tints them."))
    write(PNG_PATH, png(render()))


if __name__ == "__main__":
    main()
